
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GacXep.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Book
    {

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Book()
    {

        this.BookDetails = new HashSet<BookDetail>();

    }


    public int ProID { get; set; }

    public string ProName { get; set; }

    public int CatID { get; set; }

    public string ProImage { get; set; }

    public string NameDecription { get; set; }

    public System.DateTime CreatedDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BookDetail> BookDetails { get; set; }

    public virtual Category Category { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }

    }

}
